name: Build Package

on:
  workflow_dispatch:
    inputs:
      package:
        required: true

jobs:
   build-and-release:
     runs-on: ubuntu-latest
     steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
         with: 
           root-reserve-mb: 8192
           swap-size-mb: 8192
           remove-dotnet: 'true'
           remove-android: 'true'
           remove-haskell: 'true'
           remove-codeql: 'true'
           remove-docker-images: 'true'

       - name: Checkout
         uses: actions/checkout@v4

       - name: Build and Upload
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO_INFO: ${{ github.repository }}
         run: |
           docker run -t -v ${{ github.workspace }}:/build \
             -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
             -e REPO_INFO=${{ github.repository }} \
             archlinux:latest /bin/bash /build/scripts/build-package.sh \
             ${{ github.event.inputs.package }}
